### ISSUE TITLE
How to install ComfyUI OOTDiffusion on Windows 10？

### ISSUE THREAD

**Issue by jeffreyrobeson** [AuroBit/ComfyUI-OOTDiffusion#1]
How to install ComfyUI OOTDiffusion on Windows 10？

**Comment by 657233220** [comment]
I also want to know

**Comment by iyume** [comment]
I'm not sure if it can run on windows (assume that you had followed the instruction, it is same). I tested it on Ubuntu 22.02 / Python 3.10.x .

OOTDiffusion depends some complex thing to run, such as torch cpp_extensions. So I cannot give you a certain answer.

If you had got in trouble, feel free to open an issue.

**Comment by jeffreyrobeson** [comment]
Please provide me with a complete ComfyUI workflow .

**Comment by iyume** [comment]
[workflow.json](https://github.com/AuroBit/ComfyUI-OOTDiffusion/files/14387788/workflow.json)
@jeffreyrobeson

**Comment by iyume** [comment]
https://github.com/AuroBit/ComfyUI-OOTDiffusion/issues/2

**Comment by iyume** [comment]
https://github.com/AuroBit/ComfyUI-OOTDiffusion?tab=readme-ov-file#Windows-%E6%8C%87%E5%8D%97

Windows installation tutorial has been added.
