### ISSUE TITLE
大佬求助啊！安装后打开http://127.0.0.1:8188/提示错误

### ISSUE THREAD

**Issue by renruiw** [AuroBit/ComfyUI-OOTDiffusion#14]
我参考了好几个类似案例终于搭建好了conda虚拟环境。以下是我运行的代码：
(oms-diffusion) C:\Users\PC\ComfyUI>set CUDA_HOME=%CONDA_PREFIX%

(oms-diffusion) C:\Users\PC\ComfyUI>set CUDA_PATH=%CONDA_PREFIX%

(oms-diffusion) C:\Users\PC\ComfyUI>set CUDA
CUDA_HOME=D:\Users\PC\anaconda3\envs\oms-diffusion
CUDA_PATH=D:\Users\PC\anaconda3\envs\oms-diffusion
CUDA_PATH_V11_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
CUDA_PATH_V12_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1                                        |   0%
CUDA_PATH_V12_3=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3                                        |   0%

(oms-diffusion) C:\Users\PC\ComfyUI>
(oms-diffusion) C:\Users\PC\ComfyUI>python main.py
Total VRAM 8188 MB, total RAM 32637 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
在这之后我打开谷歌浏览器的http://127.0.0.1:8188但是提示我错误有提示窗口。写着：
When loading the graph, the following node types were not found:
OOTDGenerate
LoadOOTDPipelineHub
Nodes that have failed to load will show as red on the graph.
现在我该怎么办？大哥！

**Comment by iyume** [comment]
git clone 此仓库至 custom_nodes

**Comment by renruiw** [comment]
好的 谢谢。
