### ISSUE TITLE
Help！noob need help! / 大佬求助 CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by DENG-XC** [AuroBit/ComfyUI-OOTDiffusion#16]
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/153186602/3f72636b-091f-404a-893e-880c40e03785)
Hi, i am new to comfyui, this node can not be import when I start comfyui, I have download everything you require for windows.
大佬好，我是一名代码小白，求教这个cuda环境如何设置？谢谢

**Comment by iyume** [comment]
https://github.com/AuroBit/ComfyUI-OOTDiffusion#windows-%E6%8C%87%E5%8D%97

你看 README 了吗？
