### ISSUE TITLE
后台窗口停滞，就是没有任何反应，不报错，也没有任何输出

### ISSUE THREAD

**Issue by jinnaluo0** [AuroBit/ComfyUI-OOTDiffusion#19]
代码执行到I:\ComfyUI_windows_portable\ComfyUI\custom_nodes_bak\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py
的这个位置时
_src_path = path.join(path.dirname(path.abspath(__file__)), "src")
_backend = load(name="inplace_abn",
                extra_cflags=["-O3"],
                sources=[path.join(_src_path, f) for f in [
                    "inplace_abn.cpp",
                    "inplace_abn_cpu.cpp",
                    "inplace_abn_cuda.cu",
                    "inplace_abn_cuda_half.cu"
                ]],
                extra_cuda_cflags=["--expt-extended-lambda"])

后台窗口停滞，就是没有任何反应，不报错，也没有任何输出

**Comment by iyume** [comment]
看看新版能不能解决，新版换了 onnx 模型
