### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by cmd-d** [AuroBit/ComfyUI-OOTDiffusion#22]
(IMPORT FAILED): C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion

  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 23, in <module>
    from .pipelines_ootd.pipeline_ootd import OotdPipeline
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\pipeline_ootd.py", line 27, in <module>
    from .unet_vton_2d_condition import UNetVton2DConditionModel
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_condition.py", line 23, in <module>
    from .unet_vton_2d_blocks import (
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_blocks.py", line 23, in <module>
    from .transformer_vton_2d import Transformer2DModel
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\transformer_vton_2d.py", line 23, in <module>
    from .attention_vton import BasicTransformerBlock
  File "C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\attention_vton.py", line 21, in <module>
    from diffusers.utils import USE_PEFT_BACKEND
ImportError: cannot import name 'USE_PEFT_BACKEND' from 'diffusers.utils' (C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py)

Cannot import C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: cannot import name 'USE_PEFT_BACKEND' from 'diffusers.utils' (C:\Users\User\Comfty\ComfyUI_windows_portable_nvidia_cu121\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py)

**Comment by iyume** [comment]
Have you install via `pip install custom_nodes/ComfyUI-OOTDiffusion/requirements.txt`?

What is your diffusers version? (`pip freeze`)

**Comment by cmd-d** [comment]
C:\Users\User>python -c "import diffusers; print(diffusers.__version__)"
0.24.0

And, sure, I have pip install -r requirements.txt

**Comment by iyume** [comment]
Run `where python`. I think you are using system python to install dependencies but use ComfyUI embeded python to run ComfyUI (via `.bat` file).

**Comment by cmd-d** [comment]
Ok, so, I tried installing from ...\python_embeded\python -m pip install [requirements file]
However, now it is not loading Comfty. Here is my current setup, I really don't get what am I doing wrong.

______________________________

C:\Users\User\Comfty\ComfyUI_windows_portable\python_embeded>**nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

C:\Users\User\Comfty\ComfyUI_windows_portable\python_embeded>**pip freeze**
absl-py==2.1.0
accelerate==0.27.2
addict==2.4.0
aiofiles==23.2.1
aiohttp==3.9.3
aiosignal==1.3.1
albumentations==1.3.1
altair==5.2.0
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
anyio==4.3.0
astroid==2.15.0
async-timeout==4.0.3
attrs==23.2.0
autopep8==1.6.0
bidict==0.22.1
blinker==1.6.2
cachetools==5.3.3
cchardet==2.1.7
certifi==2024.2.2
cffi==1.16.0
cfgv==3.3.1
charset-normalizer==3.3.2
click==8.1.7
cmake==3.28.1
colorama==0.4.6
coloredlogs==15.0.1
colour-science==0.4.4
contourpy==1.2.0
cstr @ git+https://github.com/WASasquatch/cstr@0520c29a18a7a869a6e5983861d6f7a4c86f8e9b
cycler==0.12.1
Cython==3.0.2
diffusers==0.26.0
dill==0.3.7
distlib==0.3.6
docstring-to-markdown==0.11
easydict==1.10
einops==0.7.0
exceptiongroup==1.2.0
fairscale==0.4.13
fastapi==0.110.0
ffmpy @ git+https://github.com/WASasquatch/ffmpy.git@f000737698b387ffaeab7cd871b0e9185811230d
filelock==3.13.1
flake8==6.0.0
Flask==2.3.2
Flask-SocketIO==5.3.4
flatbuffers==23.5.26
fonttools==4.49.0
frozenlist==1.4.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.42
google-ai-generativelanguage==0.4.0
google-api-core==2.17.1
google-auth==2.28.2
google-generativeai==0.4.0
googleapis-common-protos==1.63.0
gradio==4.16.0
gradio_client==0.8.1
grpcio==1.62.1
grpcio-status==1.48.2
h11==0.14.0
httpcore==1.0.4
httpx==0.27.0
huggingface-hub==0.21.4
humanfriendly==10.0
identify==2.5.24
idna==3.6
imageio==2.34.0
img2texture @ git+https://github.com/WASasquatch/img2texture.git@a546609a915caf1dcb84a15bf44b5b639ad924e6
importlib-metadata==7.0.1
importlib_resources==6.1.2
insightface==0.7.3
install==1.3.5
isort==5.12.0
itsdangerous==2.1.2
jax==0.4.25
jedi==0.18.2
jieba==0.42.1
Jinja2==3.1.3
joblib==1.3.2
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
lazy-object-proxy==1.9.0
lazy_loader==0.3
llvmlite==0.42.0
loguru==0.7.2
Markdown==3.4.4
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.3
mccabe==0.7.0
mdurl==0.1.2
mediapipe==0.10.11
ml-dtypes==0.3.2
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.15
networkx==3.2.1
ninja==1.11.1.1
nodeenv==1.8.0
numba==0.59.0
numpy==1.24.4
nvidia-ml-py3==7.352.0
omegaconf==2.3.0
onnx==1.14.1
onnxruntime==1.17.1
openai==0.27.8
opencv-contrib-python==4.9.0.80
opencv-python==4.7.0.72
opencv-python-headless==4.7.0.72
opt-einsum==3.3.0
orjson==3.9.15
packaging==24.0
pandas==2.2.1
parso==0.8.3
pilgram==1.2.1
Pillow==9.5.0
platformdirs==3.5.3
pluggy==1.2.0
pooch==1.8.1
pre-commit==3.3.3
prettytable==3.8.0
proto-plus==1.23.0
protobuf==3.20.3
psutil==5.9.8
pyarrow==13.0.0
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycodestyle==2.10.0
pycparser==2.21
pydantic==2.6.3
pydantic_core==2.16.3
pydocstyle==6.2.3
pydub==0.25.1
pyflakes==3.0.1
pygame==2.5.1
pygit==0.1
pygit2==1.14.1
Pygments==2.17.2
pylint==2.17.0
PyMatting==1.1.12
pyparsing==3.1.2
pyreadline3==3.4.1
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-engineio==4.5.1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.7.1
python-multipart==0.0.9
python-socketio==5.8.0
pytoolconfig==1.2.5
pytz==2024.1
PyWavelets==1.4.1
PyYAML==6.0.1
qudida==0.0.4
referencing==0.33.0
regex==2023.12.25
rembg==2.0.55
requests==2.31.0
retrying==1.3.4
rich==13.7.1
rope==1.7.0
rpds-py==0.18.0
rsa==4.9
ruff==0.3.0
safetensors==0.4.2
scikit-image==0.20.0
scikit-learn==1.3.0
scipy==1.12.0
segment-anything==1.0
semantic-version==2.10.0
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
snowballstemmer==2.2.0
sounddevice==0.4.6
starlette==0.36.3
sympy==1.12
tenacity==8.2.2
threadpoolctl==3.2.0
tifffile==2024.2.12
tiktoken==0.4.0
timeout-decorator==0.5.0
timm==0.9.16
tokenizers==0.13.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.12.0
toolz==0.12.1
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchsde==0.2.6
torchvision==0.15.2+cu118
tqdm==4.66.2
trampoline==0.1.2
transformers==4.26.1
typer==0.9.0
typer-config==1.4.0
typing_extensions==4.10.0
tzdata==2024.1
ujson==5.7.0
urllib3==2.2.1
uvicorn==0.27.1
virtualenv==20.23.0
wcwidth==0.2.6
websockets==11.0.3
Werkzeug==2.3.6
wget==3.2
whatthepatch==1.0.4
win32-setctime==1.1.0
wrapt==1.15.0
xxhash==3.3.0
yapf==0.32.0
yarl==1.9.4
zipp==3.17.0

**Comment by longgui0318** [comment]
look this  [issue](https://github.com/levihsu/OOTDiffusion/issues/44)

**Comment by iyume** [comment]
Do you see your `diffusers==0.26.0` which is incompatible with `diffusers==0.24.0`? It is a issue about your environment management.

Use conda and start ComfyUI via `conda activate <env>` and `python main.py` manually.

**Comment by Aukture** [comment]
this error may be because of : Ninja is required to load C++ extensions. 
Check in your compfyui terminal
