### ISSUE TITLE
Which models to download?

### ISSUE THREAD

**Issue by RYG81** [AuroBit/ComfyUI-OOTDiffusion#23]
hi,
Which models to download? Please help.

**Comment by iyume** [comment]
https://github.com/levihsu/OOTDiffusion

**Comment by RYG81** [comment]
Bro I tried to download their hugging face data but in comfy node it is not taking the folder

**Comment by iyume** [comment]
`Load OOTDiffusion from Hub` is used to load from hub.
`Load OOTDiffusion Local` is used to load from local folder.

**Comment by RYG81** [comment]
Load OOTDiffusion from Hub works fine, but i want to use local. I have downloaded all data from hugging face but still not working
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/45922094-a739-4ed7-b9d9-4a958ec91dc4)

**Comment by iyume** [comment]
Your directory should look like:

![图片](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/48091591/a748582b-886d-479c-8824-f2118e5cda47)

**Comment by RYG81** [comment]
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/7728ed8c-8b46-49ad-bcc5-fa737b50078f)
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/cff0f821-3eb4-49e3-aa4b-13408281a513)
I have same structure still get above error

**Comment by iyume** [comment]
pls, take more infomation in your screenshot, with path, and your input to ComfyUI node

**Comment by RYG81** [comment]
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/8ad7b628-a365-4bfc-b606-ee990bbd8518)
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/6f3dbd57-5b9c-427d-8172-7f4752bf9b9d)
[OOTDiffusion.json](https://github.com/AuroBit/ComfyUI-OOTDiffusion/files/14585774/OOTDiffusion.json)
I hope all these helps

**Comment by iyume** [comment]
Start python interpreter under your ComfyUI root directory. Try follow commands:

```
import os
paths = os.listdir('models')
print(paths)
print('OOTDiffusion' in paths)
print(os.path.isdir('models/OOTDiffusion'))
```

**Comment by RYG81** [comment]
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/8ab3f4b0-5d57-4505-9acd-69e6b0127d36)

**Comment by iyume** [comment]
Use `ComfyUI/models/OOTDiffusion`, not `models/OOTDiffusion`

**Comment by RYG81** [comment]
Thank you, it started working.
I stared the repository. :)
Just last question
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/10570236/ec221272-32d5-4e61-af79-6f14f5f39fae)
What is it downloading now?

**Comment by iyume** [comment]
`https://huggingface.co/openai/clip-vit-large-patch14` this one

**Comment by RYG81** [comment]
Where is need to be copied? Just wanted to know so that I don't delete by mistake.

**Comment by iyume** [comment]
The default huggingface cache folder is `~/.cache/huggingface` in linux or `%HOMEPATH%\.cache\huggingface` in windows

**Comment by RYG81** [comment]
I mean where it should be in Comfy folder as I do not have space in OS drive, i normally delete cache data.

**Comment by iyume** [comment]
There is no such option for this. Maybe future.

**Comment by iyume** [comment]
Maybe https://huggingface.co/docs/huggingface_hub/guides/manage-cache is what you need, just set `HF_HUB_CACHE` environment.
