### ISSUE TITLE
Model Download location

### ISSUE THREAD

**Issue by kakachiex2** [AuroBit/ComfyUI-OOTDiffusion#25]
Were are the model downloaded I already have it in another implementation and don't wants duplicate models so I can use the one already downloaded.

**Comment by kakachiex2** [comment]
I'm trying to use the local directory node and I get this error; I create a sys link folder with the model from the others OTTDiffusion model location is the same structure.

Error occurred when executing LoadOOTDPipeline:

input path models\OOTDiffusion is not a directory

File "C:\ComfyUI_Cloth\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_Cloth\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_Cloth\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_Cloth\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 59, in load
return (self.load_impl(type, path),)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_Cloth\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 55, in load_impl
raise ValueError(f"input path {path} is not a directory")

Close

**Comment by iyume** [comment]
Maybe duplicated at https://github.com/AuroBit/ComfyUI-OOTDiffusion/issues/23

Use `ComfyUI/models/OOTDiffusion`, not `models/OOTDiffusion`
