### ISSUE TITLE
Can't load nodes!!

### ISSUE THREAD

**Issue by red-sponge** [AuroBit/ComfyUI-OOTDiffusion#26]
![스크린샷 2024-03-14 134825](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/127950543/ca99bd01-f5e5-4535-908d-9036deccee03)
![스크린샷 2024-03-14 135402](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/127950543/50a806b6-6155-4d43-ae35-c5f4062acb0b)

Please help me!

**Comment by iyume** [comment]
The original OOTDiffusion is depended on `diffusers=0.24`.

Can you show your diffusers version?

**Comment by red-sponge** [comment]
Mine is diffusers==0.26.3

![스크린샷 2024-03-14 144906](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/127950543/ea8d3f7e-bf02-45d4-a6de-f0beefe43845)

**Comment by iyume** [comment]
Your diffusers may be conflicted with other custom nodes.

You can try switch to `diffusers-0.26` branch:

```
cd custom_nodes/ComfyUI-OOTDiffusion
git pull origin diffusers-0.26
git switch diffusers-0.26
```
