### ISSUE TITLE
Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes

### ISSUE THREAD

**Issue by ClaudeFANN** [AuroBit/ComfyUI-OOTDiffusion#27]
Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

求教这是要如何解决？

**Comment by iyume** [comment]
See: https://github.com/AuroBit/ComfyUI-OOTDiffusion/issues/26

Your diffusers may be conflicted with other custom nodes.

You can try switch to `diffusers-0.26` branch:

```
cd custom_nodes/ComfyUI-OOTDiffusion
git pull origin diffusers-0.26
git switch diffusers-0.26
```
