### ISSUE TITLE
Processing images with sizes other than 768x1024 will distort the results

### ISSUE THREAD

**Issue by pvbang** [AuroBit/ComfyUI-OOTDiffusion#29]
Thanks, is there any way to handle the fact that images with sizes other than 768x1024 will distort the results? 
![Screenshot 2024-03-19 072818](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/89725712/f1df6234-c0cb-4846-9bac-b4f6f9ed14d0)

I tried processing the input image (human) by putting that image into another image of size 768x1024 but with large images it doesn't work very well, is there any way to handle this?
![Screenshot 2024-03-19 072713](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/89725712/78b952ce-d2cd-49f3-b8fc-b144898ac178)

**Comment by iyume** [comment]
The original OOTDiffusion resized the images, so I think you should open an issue on https://github.com/levihsu/OOTDiffusion

https://github.com/levihsu/OOTDiffusion/blob/344112ad1c03c2af1cf7a1f07d689b18af4c175a/run/run_ootd.py#L59-L60

**Comment by pvbang** [comment]
I just found a way to fix it, just resize the result :)
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/89725712/50a9a48c-387a-4d70-9f19-7f4b6cb2d746)
