### ISSUE TITLE
error when executing

### ISSUE THREAD

**Issue by kinggeorge05** [AuroBit/ComfyUI-OOTDiffusion#4]
![error](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/157688513/2a5e7aac-c376-41f1-9bd1-a3be1b28e2c5)

Hey I got this error when trying this out

**Comment by iyume** [comment]
Follow the instruction https://github.com/AuroBit/ComfyUI-OOTDiffusion#instruction-%E6%8C%87%E5%8D%97 to download the repository into models/OOTDiffusion folder.

**Comment by iyume** [comment]
A new node "Load OOTDiffusion from Hub" is recently added which aimed to download model automatically.
