### ISSUE TITLE
用本地模式填写路径的时候要怎么填

### ISSUE THREAD

**Issue by ghosthzhen** [AuroBit/ComfyUI-OOTDiffusion#40]
Error occurred when executing LoadOOTDPipeline:

[ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from G:\comfyUI\ood_\checkpoints\checkpoints\humanparsing\parsing_atr.onnx failed:Load model G:\comfyUI\ood_\checkpoints\checkpoints\humanparsing\parsing_atr.onnx failed. File doesn't exist

**Comment by iyume** [comment]
和 https://huggingface.co/levihsu/OOTDiffusion 一致

**Comment by nxhy** [comment]
解决了吗，具体是啥
