### ISSUE TITLE
如果从本地加载模型，具体的路径应该是怎样的？

### ISSUE THREAD

**Issue by lger4567** [AuroBit/ComfyUI-OOTDiffusion#44]
你好，感谢你写了这个插件。
已经自动下载了模型也能正常工作，但模型一直在.cach里很担心。
我发现有个节点叫Load OOTDiffusion Local，看起来像是从本地加载模型。

我也手动下载了模型，和.cach里的模型，看起来并不一样，但都有很多层子目录和文件。
是应该把哪套模型的文件放在models\OOTDiffusion中呢？那些很长的多层目录具体该从哪一级剪切过去呢？

如能指点，非常感谢！

**Comment by gaoming714** [comment]
same issues. I know the owner says download OOTDiffusion and clip-vit-large-patch14.(it will download model to cache)
But can you show the manual way to download these file to which folder.

**Comment by gaoming714** [comment]
First download levihsu/OOTDiffusion to **ComfyUI/models/**

    repo_id = "levihsu/OOTDiffusion"
    repo_revision = "d33c517dc1b0718ea1136533e3720bb08fae641b"

![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/7444968/fa708cd7-f21b-470e-9482-02c9f31157b5)

Second download openai/clip-vit-large-patch14  to **ComfyUI/models/OOTDiffusion/clip-vit-large-patch14/**
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/7444968/5fd0ae82-3cc3-4ddf-9086-b9597a7e23e9)

Last you must config VIT_PATH in file **ComfyUI/custom_nodes/ComfyUI-OOTDiffusion/inference_ootd.py**
change   **VIT_PATH = f"openai/clip-vit-large-patch14"** to **VIT_PATH = Path(root) / "clip-vit-large-patch14"**
this file defined the VIT_PATH in this custom node, root path is ComfyUI/models/OOTDiffusion/
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/7444968/fc139092-b7e2-4754-a445-8e97941abb54)

**Comment by gaoming714** [comment]
> 你好，感谢你写了这个插件。 已经自动下载了模型也能正常工作，但模型一直在.cach里很担心。 我发现有个节点叫Load OOTDiffusion Local，看起来像是从本地加载模型。
> 
> 我也手动下载了模型，和.cach里的模型，看起来并不一样，但都有很多层子目录和文件。 是应该把哪套模型的文件放在models\OOTDiffusion中呢？那些很长的多层目录具体该从哪一级剪切过去呢？
> 
> 如能指点，非常感谢！

上面讲解了使用local的方法，不过我个人感觉 local和Hub各有优劣，我本来也用的local，现在转型到Hub了。

@iyume 请关闭这个issues吧

**Comment by iyume** [comment]
vit 的载入不应该和此仓库相关，而需要一个统一的 diffusers 接口实现，这也是 ComfyUI 本身对 diffusers 支持存在的一个问题。
这边最多加一个 optional 连接，但解决不了根源。

**Comment by iyume** [comment]
谢谢帮助，有问题随时在此 issue 下回复。

**Comment by lijiahua235** [comment]
![image](https://github.com/user-attachments/assets/b117f027-3331-4105-a14f-8884bf0ee12b)
我用了上面的方法来放置文件，也修改了inference_ootd.py   为什么还是会报错
![image](https://github.com/user-attachments/assets/cf1b3b94-1fed-4c12-bfcb-456c43ebad66)
