### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by biek12** [AuroBit/ComfyUI-OOTDiffusion#5]
Inconsistent model_image size (800, 800) != (768, 1024)
Inconsistent cloth_image size (3588, 4783) != (768, 1024)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI-aki-v1.1\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI\ComfyUI-aki-v1.1\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI\ComfyUI-aki-v1.1\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 94, in generate
    keypoints = OpenPose()(model_image.resize((384, 512)))
  File "D:\ComfyUI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-OOTDiffusion\openpose\run_openpose.py", line 48, in __call__
    subset = pose['bodies']['subset'][0][:18]
IndexError: list index out of range

Prompt executed in 2.33 seconds

**Comment by mhedra** [comment]
Hello @biek12,

Any clue how you by passed the above error ?
I have used the following image sizes:
<img width="1033" alt="image" src="https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/5819192/7ba74e10-6bf6-4e20-8db4-721156951dff">

Are we forced to use specific sizes or it the function will resize before continuing the execution or maybe we can change the code directly to support any sizes ?

Thanks

**Comment by iyume** [comment]
@mehdimj This error is raised from openpose, which means that you passed incorrect model_image for openpose to recognize its body.

**Comment by mhedra** [comment]
@iyume 
Thanks for the feedback
I will debug on that level and go from there.
Cheers
