### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by ghost** [AuroBit/ComfyUI-OOTDiffusion#6]
Firstly thanks for this, very helpful.

I wanted to confirm about it's license, this repo has Apache license but the original model has non commercial license.
So, can we use it?

**Comment by iyume** [comment]
No, you must obey the terms of [CC-BY-NC-SA-4.0](https://spdx.org/licenses/CC-BY-NC-SA-4.0.html).

It's my mistake not copying the original license. I will update the license soon.
